### ISSUE TITLE
Update mark positions

### ISSUE THREAD

**Issue by prashantShrivastava91** [brightec/JMMarkSlider#5]
How can mark positions be updated once UISlider is drawn??

**Comment by Shanlon** [comment]
From using this framework briefly it seems to not allow you too, since it creates the slider's background as UIImage's. I was having an issue with re-drawing the slider since you need to handle this with orientation changes. When you need to make an update, remove it from its super view, then add your updated slider. Make sure to add your positions before it is added to the view, otherwise you will not be able to make changes since they are images.

**Comment by prashantShrivastava91** [comment]
Thanks Shanlon. Great to get reply from you so soon. Will take care of it while updating slider... :+1:
